def execute(resources,state):
    r"""Enable\Disable the Kodi extension KodiLifxAmbilight."""
    import time
    enabled = True if state else False
    print "kodi_lifx_ambilight:: ",'state:',state,', enabled:',enabled
    resources.interfaces["Kodi"].addon_enable(u'script.kodi.lifx.ambilight',enabled)
    current_lights = resources.interfaces["Lifx"].get_state()
    resources.interfaces["Lifx"].set_all(0, 1, 1, kelvin=3000, power=True)
    time.sleep(1)
    resources.interfaces["Lifx"].set_state(current_lights)